config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  # Named Routes
  get  '/register', to: 'users#new'         # Here, NOT below in resources
  get  '/login',    to: 'sessions#new'
  post '/login',    to: 'sessions#create'   # do need to post something here w/form_tag
  get  '/logout',   to: 'sessions#destroy'  # we can use a get here, because no need to delete anything
  get  '/pin',      to: 'sessions#pin'
  post '/pin',      to: 'sessions#pin'


  # Resources
  resources     :users,       except: [:index, :destroy]
  resources     :categories,    only:  [:new, :create, :show]
  resources     :posts,       except: [:destroy] do
    member do
      post      :vote   #/posts/id/vote
    end
    resources   :comments,      only:   [:create, :index] do #/posts/id/comments/id
      member do
        post :vote   #/posts/id/comments/id/vote
      end
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include VotableClintMarch  # Includes Association & Instance Methods

  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :post

  validates :user_id, presence: true
  validates :post_id, presence: true
  validates :body,    presence: true,
                      length:   { maximum: 300 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_logged_in

  def vote
    post = Post.find_by(slug: params[:post_id])
    @comment = Comment.find(params[:id])
    vote = Vote.create(votable: @comment, creator: current_user, vote: params[:vote])
    respond_to do |format|
      format.html do
        if vote.valid?
          flash[:success] = 'Vote counted.'
        else
          flash[:error] = "You've already voted on that commment."
        end
        redirect_to :back
      end

      #Alternate approach rendering partial of vote.js.erb in shared instead of on view
      format.js do
        if !vote.valid?
          render 'shared/vote_error', locals: { type: "comment"}
        end
      end
    end
  end

  def create
    #This is possible due to association - so it passes it's foreign_key info
    @post = Post.find_by(slug: params[:post_id])
    #SAVE THROUGH THE ASSOCIATION TO AVOID EXPLICITLY SETTING KEYS!!!!
    @comment = @post.comments.build(params.require(:comment).permit(:body))
    @comment.creator = current_user
    if @comment.save
      flash[:success] = "Comment Saved!"
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end
end

app/views/comments/_comment.html.erb
<% link ||= false %>

<div class='row'>
  <div class='span1 well text-center'>
    <% if logged_in? %>
      <%= link_to vote_post_comment_path(comment.post, comment, vote: 'true'), method: 'post', remote: true do %>
        <span class='icon-chevron-up'></span>
      <% end %>
    <% end %>
    <br/>
    <span id='comment_<%= comment.id %>_votes'>
      <%= pluralize(comment.net_votes, 'vote') %>
    </span>
    <br/>
    <% if logged_in? %>
      <%= link_to vote_post_comment_path(comment.post, comment, vote: 'false'), method: 'post', remote: true do %>
        <span class='icon-chevron-down'></span>
      <% end %>
    <% end %>
    <span></span>
  </div>
  <div class='span6 well'>
    <p> "<%= comment.body %>"
      <% if link %>
        <span> on <%= link_to comment.post.title, post_path(comment.post) %> </span>
      <% end %>
    </p>
    <p>
      <span class='quiet'>
        by <%= comment.creator.username %>
      </span>
      <small> on <%= format_datetime(comment.created_at) %> </small>
    </p>
  </div>
</div>

app/views/comments/vote.js.erb
$("#comment_<%= @comment.id %>_votes").html("<%= pluralize(@comment.net_votes, 'vote') %>");