config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  # Named Routes
  get  '/register', to: 'users#new'         # Here, NOT below in resources
  get  '/login',    to: 'sessions#new'
  post '/login',    to: 'sessions#create'   # do need to post something here w/form_tag
  get  '/logout',   to: 'sessions#destroy'  # we can use a get here, because no need to delete anything
  get  '/pin',      to: 'sessions#pin'
  post '/pin',      to: 'sessions#pin'


  # Resources
  resources     :users,       except: [:index, :destroy]
  resources     :categories,    only:  [:new, :create, :show]
  resources     :posts,       except: [:destroy] do
    member do
      post      :vote   #/posts/id/vote
    end
    resources   :comments,      only:   [:create, :index] do #/posts/id/comments/id
      member do
        post :vote   #/posts/id/comments/id/vote
      end
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  include VotableClintMarch # Includes Association & Instance Methods
  include SluggableCjn # Includes Callback & Instance Methods & Attr "slug_column"

  sluggable_column :title

  belongs_to  :creator, foreign_key: 'user_id', class_name: 'User'
  has_many    :comments
  has_many    :post_categories
  has_many    :categories, through: :post_categories


  validates :url,         presence: true,
                          uniqueness: true  #REGEX CHECK
  validates :description, presence: true,
                          length: { minimum: 2, maximum: 500}
  validates :title,       presence: true,
                          length: { minimum: 2, maximum: 140 }
  validates :user_id,     presence: true   #HOW DO I SPECIFY THIS ONE USING CREATOR?
  #validates :categories    #HOW DO I VALIDATE THROUGH A JOIN TABLE? Need to verify cats.
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post,            only: [:show, :edit, :update, :vote]
  before_action :set_categories,      only: [:edit, :new]

  before_action :require_logged_in,     only: [:new, :create, :vote]
  before_action :require_correct_user,  only: [:edit, :update]

  ########################## DISPLAYING EXISTING POSTS #########################
  def index
    @posts = Post.all.sort_by(&:net_votes).reverse
    @categories = Category.all
  end

  def show
    @comment = Comment.new
    respond_to do |format|
      format.html
      format.json { render json: [@post.title, @post.id]  }
      format.xml  { render  xml: [@post.title, @post.id] }
      format.js   { render   js: @post.title }
    end
  end

  ############################ MAKING NEW POSTS ################################
  def new
    @post = Post.new
  end

  def create
    post = Post.new(post_params)
    post.creator = current_user
    if post.save
      flash[:success] = "Your post was created"
      redirect_to posts_path
    else
      render 'new'
    end
  end

  ############################## MODIFYING POSTS ###############################
  def edit
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Changes Saved"
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def vote
    @vote = Vote.create(votable: @post, creator: current_user, vote: params[:vote])
    respond_to do |format|
      format.html do
        if @vote.valid?
          flash[:success] = 'Vote counted.'
        else
          flash[:error] = "You've already voted on this post."
        end
        redirect_to :back
      end
      format.js   #THIS TRIPS OUR VOTE.JS.ERB FILE IN POSTS
    end
  end

  ###################### POST CONTROLLER METHODS (PRIVATE) #####################
  private
    def require_correct_user
      unless (current_user?(@post.creator) || admin_user?)
        flash[:error] = 'You must be the creator of this post to do that.'
        redirect_to root_path
      end
    end

    def post_params
      params.require(:post).permit(:title, :url, :description, category_ids: [])
    end

    def set_categories
      @categories = Category.all
    end

    def set_post
      @post = Post.find_by(slug: params[:id])
    end
end

app/views/posts/_form.html.erb
<div class='span7 well'>
  <%= form_for @post do |f| %>
    <%= render 'shared/form_errors', object: f.object %>

    <%= f.label       :title %>
    <%= f.text_field  :title %>
    <%= f.label       :url %>
    <%= f.text_field  :url %>
    <%= f.label       :description %>
    <%= f.text_area   :description, rows: 8, class: 'span5' %>
    <br/>

    <%= f.collection_check_boxes :category_ids, @categories, :id, :name do |ckbx|%>
      <%= ckbx.label(class: 'checkbox inline') {ckbx.check_box(class: 'checkbox') + ckbx.text } %>
    <% end %>
    <br/>
    <br/>

    <%= f.submit button_name, class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class='row'>
  <div class='span1 well text-center'>
    <% if logged_in? %>
      <%= link_to vote_post_path(post, vote: true), method: 'post', remote: true do %>
        <span class='icon-chevron-up'></span>
      <% end %>
    <% end %>
    <br/>
    <span id='post_<%= post.slug %>_votes'>
      <%= pluralize(post.net_votes,'vote') %>
    </span>
    <br/>
    <% if logged_in? %>
      <%= link_to vote_post_path(post, vote: false), method: 'post', remote: true do %>
        <span class='icon-chevron-down'></span>
      <% end %>
    <% end %>
  </div>
  <div class='span8 well'>
    <p>
      <%= render post.categories %>
    </p>
    <h4> <%= link_to post.title, format_url(post.url) %> </h4>
    <p>  <%= post.description             %> </p>

    <!-- Make A _creator_sig.html.erb
         FIX THE ANONYMOUS TEMP SOLUTION ONCE DB IS RESET
      -->
    <p>
      <span class='quiet'> posted by
        <%= (post.creator.nil? ? "Anonymous" : post.creator.username) %>
      </span>
      <small class='quiet'> on <%= format_datetime(post.created_at) %> </small>
    </p>

    <small>
      <span>
        <%= link_to "#{pluralize(post.comments.size, 'comment')}", post_path(post) %>
      </span>
      <% if current_user?(post.creator) || admin_user? %>
          |
        <span class='quiet'>
          <%= link_to 'edit post', edit_post_path(post) %>
        </span>
      <% end %>
    </small>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render '/shared/content_title', title: "Edit Post" %>

<%= render 'form', button_name: "Update" %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: "All Posts" %>

<% if !@posts.empty? %>
    <%= render @posts %>
<% end %>

app/views/posts/new.html.erb
<%= render '/shared/content_title', title: "Create New Post" %>

<%= render 'form', button_name: "Create" %>

app/views/posts/show.html.erb
<% if (logged_in? and current_user?(@post.creator)) || admin_user? %>
  <p class='pull-right'>
    [<%= link_to 'edit post', edit_post_path(@post) %>]
  </p>
<% end %>

<p> <%= render @post.categories %> </p>

<%= render 'shared/content_title.html.erb', title: @post.title,
                                            link: format_url(@post.url),
                                            title2: nil %>

<p>
  <%= @post.description %>
</p>
<hr/>

<% if logged_in? %>
  <div class='row span8'>
    <h5> Leave Comment </h5>
    <%= form_for [@post, @comment] do |f| %>
      <%= render 'shared/form_errors', object: f.object %>

      <%= f.text_area   :body, rows: 4, class: 'span4' %>
      <br/>
      <%= f.submit "Submit", class: "btn btn-small btn-primary" %>
      <span class='quiet'><b id='countdown'> </b></span>
    <% end %>
  </div>
<% end %>

<div class='row span8'>
  <% if !Post.find(@post).comments.empty? %>
    <h4>Comments:</h4>
    <%= render @post.comments %>
  <% end %>
</div>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
  $('#post_<%= @post.slug %>_votes').html("<%= pluralize(@post.net_votes, 'vote') %>");
<% else %>
  alert("You can only vote on a post once.")
<% end %>