config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  # Named Routes
  get  '/register', to: 'users#new'         # Here, NOT below in resources
  get  '/login',    to: 'sessions#new'
  post '/login',    to: 'sessions#create'   # do need to post something here w/form_tag
  get  '/logout',   to: 'sessions#destroy'  # we can use a get here, because no need to delete anything
  get  '/pin',      to: 'sessions#pin'
  post '/pin',      to: 'sessions#pin'


  # Resources
  resources     :users,       except: [:index, :destroy]
  resources     :categories,    only:  [:new, :create, :show]
  resources     :posts,       except: [:destroy] do
    member do
      post      :vote   #/posts/id/vote
    end
    resources   :comments,      only:   [:create, :index] do #/posts/id/comments/id
      member do
        post :vote   #/posts/id/comments/id/vote
      end
    end
  end
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :success ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li> <%= link_to "Postit!", root_path, :class => 'brand' %> </li>
  <% if logged_in? %>
    <li> <%= link_to 'New Post', new_post_path %> </li>
  <% end %>
  <li>
    <div class='btn-group nav_item' id='navcatdropdown'>
      <a class='btn btn-small dropdown-toggle' data-toggle='dropdown' href="#">
        Categories
        <i class='caret'></i>
      </a>
      <ul class='dropdown-menu'>
        <% @categories.each do |category| %>
          <li> <%= link_to category.name, category_path(category) %> </li>
        <% end %>
        <% if admin_user? %>
          <li class='divider'></li>
          <li>
            <%= link_to(new_category_path) do %>
              <i class='icon-plus'></i>
              New Category
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </li>

  <% if !logged_in? %>
    <li>
      <div class:'nav_item'>
        <%= link_to 'Register', register_path, class: 'btn btn-small btn-success' %>
      </div>
    </li>
    <li>
      <div class='nav_item'>
        <%= link_to 'Login', login_path, class: 'btn btn-small' %>
      </div>
    </li>

  <% else #logged in%>
    <li>
      <div class='btn-group nav_item' id='navuserdropdown'>
        <a class='btn btn-small dropdown-toggle' data-toggle='dropdown' href="#">
          <%= current_user.username %>
          <i class='caret'></i>
        </a>
        <ul class='dropdown-menu'>
          <li>
            <%= link_to edit_user_path(current_user) do %>
              <i class="icon-pencil"></i>
              <span>edit profile</span>
            <% end %>
          </li>
          <li>
            <%= link_to user_path(current_user) do %>
              <i class='icon-user'></i>
              <span>view profile </span>
            <% end %>
          </li>
          <li>
            <%= link_to logout_path do %>
            <i class='icon-off'></i>
            <span>logout</span>
            <% end %>
          </li>
        </ul>
      </div>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Postit!</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>